# Generated by Django 6.1.1 on 2026-09-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0007_foodorder_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], max_length=20, null=True),
        ),
    ]
